
const events = [

{
id: 1,
date: "2025-03-08",
endDate: "2025-03-09",
name: "HackHer Hackathon",
timeplace: "Queen's University, hybrid",
info: "Hackher applications are open! Go to the Hackher page or our LinkTree to access the application form. Keep an eye out for pre-hackathon events!",
img: "/events/hackher_event.png",
cardColor: "pink",
},
{
id: 2,
date: "2025-03-01",
name: "HackHer Prep Workshop",
timeplace: "Jeffrey Hall, Room 128",
info: "Want to brush up on your technical skills, learn some new techniques, or start right at the beginning with starting a project? Join us for the hackHer 2025 Prep Workshop!",
img: "/events/hackher_prep.png",
cardColor: "blue",
},
{
id: 3,
date: "2025-02-28",
name: "HackHer Team Building Cafe",
timeplace: "CasLab, Goodwin Hall",
info: "Join us in the caslab for our cafe-themed pre-hackathon event! Find a team if you haven’t already, those who do have a team are also encouraged to come!",
img: "/events/hackher_cafe.png",
cardColor: "purple",
},
{
id: 4,
date: "2025-02-04",
name: "QWIC x COMPSA Karaoke",
timeplace: "The Mansion",
info: "Gather for a night out at The Mansion (19+ Venue). Perform to your hearts content or just hang out, all are welcome! RSVP on the form in our LinkTree, FREE ENTRY!",
img: "/events/karaoke.png",
cardColor: "pink",
},
{
id: 5,
date: "2024-11-19",
name: "Women at Microsoft Fireside Chat",
timeplace: "MacCorry D214, 12pm-1pm",
info: "Join us for a panel of female leaders at Microsoft, discussing career growth, resiliency, and empowerment!",
img: "/events/fireside_chat.png",
cardColor: "blue",
},
{
id: 6,
date: "2024-11-09",
name: "QWIC x SpinCo",
timeplace: "SpinCo Kingston, 3pm",
info: "SpinCo is back! To secure your spot, sign up via our linktree and e-transfer to finance@qwic.org . We cant wait!",
img: "/events/spinco_2024.jpeg",
cardColor: "purple",
},
{
id: 7,
date: "2024-09-23",
name: "Meet the Mentors Game Night",
timeplace: "CasLab, 6-7:30pm",
info: "Interested in becoming a mentee in our bits and bytes mentorship program? Join us for a night of games and meet the mentors!",
img: "/events/meet_mentors.png",
cardColor: "pink",
},
{
id: 8,
date: "2024-09-15",
name: "Bracelet Making",
timeplace: "MacDonald Park, 12-2pm",
info: "Kick off the school year with bracelet making with QWIC! Join us in MacDonald Park near the tube sculpture.",
img: "/events/bracelet_making_event.png",
cardColor: "blue",
},
{
id: 9,
date: "2024-04-03",
name: "GitPub",
timeplace: "DAFT Brewing, 10pm-2am",
info: "Join us for a night out of dancing and singing at DAFT brewing! Tickets are $15 through the link in our Instagram bio.",
img: "/events/gitpub.jpg",
cardColor: "pink",
},
{
id: 10,
date: "2024-03-09",
endDate: "2024-03-10",
name: "HackHer",
info: "QWIC's annual Hackathon is coming this March! Applications open Feb 2, 2024. Stay tuned for panels, sponsors and other details!",
img: "/events/hackher.jpg",
cardColor: "blue",
},
{
id: 11,
date: "2024-02-11",
name: "QWIC x SpinCo",
timeplace: "SpinCo Kingston, 1:30pm",
info: "We had such a blast last semester at spinco that WE HAD to bring it back! Tickets are live in our Instagram bio, get them before they sell out!",
img: "/events/spinco_feb.jpg",
cardColor: "purple",
},
{
id: 12,
date: "2023-11-15",
name: "Technical Internship Panel",
info: "Interested in learning what goes on during an internship? Meet panelists from companies such as Microsoft, Whitehorse Liquidity Partners, Bank of Canada, Toronto Blue Jays and more!",
img: "/events/techpanel.jpg",
cardColor: "pink",
},
{
id: 13,
date: "2023-11-04",
name: "QWIC x SpinCo",
timeplace: "SpinCo Kingston, 3pm",
info: "QWIC takes over SpinCo! Going to be super fun with great music and even better vibes. Tickets are $15 through the link in our Instagram bio, get them before they sell out!",
img: "/events/spinco_nov.jpg",
cardColor: "blue",
},
{
id: 14,
date: "2023-09-16",
name: "Bracelet Making",
timeplace: "MacDonald Park, 1-3pm",
info: "Kick the year off by joining us at MacDonald Park from 1-3pm for some bracelet making! All are welcome, come meet people or bring a friend!",
img: "/events/braceletmaking.jpg",
cardColor: "purple",
},
{
id: 15,
date: "2025-09-08",
name: "Beading In The Park",
timeplace: "Macdonald Park, 5:30-7:30",
info: "Join QWIC for our first event of the school year!   Get the chance to meet the community with board games and bracelets!",
img: "/events/beadinginthepark.png",
cardColor: "purple",
},
{
id: 16,
date: "2025-10-28",
name: "Lucky Charm Keychains",
timeplace: "CasLab, 6pm",
info: "Join us for a fun key-chain making and craft night!",
img: "/events/keychains.png",
cardColor: "purple",
},
{
id: 17,
date: "2025-11-05",
name: "Resume Workshop",
timeplace: "Goodwin Hall CasLab, 7pm",
info: "Join us on November 5 at 7 PM in the CasLab in Goodwin Hall for our Resume Workshop! We’ll walk you through how to craft a strong, professional resume from the ground up!",
img: "/events/resume.png",
cardColor: "purple",
},
{
id: 18,
date: "2026-01-13",
name: "QWIC x QUX Vision Board Night",
timeplace: "Goodes Room 302, Free",
info: "Join QWIC and QUX for a creative evening where you'll learn the basics of Figma while designing your own personalized vision board for 2026! Perfect for beginners - no design experience needed. Bring your goals, dreams, and creativity!",
img: "/events/qux x qwic - vision board.png",
cardColor: "blue",
},
{
id: 19,
date: "2026-02-11",
name: "Pitch Your Friend",
timeplace: "Daft Brewing - 10pm",
info: "Come pitch your single friends in front of a crowd, watch everyone mingle, and see what happens. Join us February 11th at 10PM at Daft Brewing!",
img: "/events/pitch your friend!.png",
cardColor: "purple",
},
{
id: 20,
date: "2025-12-08",
name: "QWIC x Ericsson Info Session",
timeplace: "Goodes Room 118",
info: "Join us for an information session with Ericsson to learn about career opportunities, company culture and their innovative work in telecommunications and technology.",
img: "/events/QWIC X ERICSSON Info Session.png",
cardColor: "pink",
}
];

export default events;