services:
  postgres:
    image: postgres:16.3-alpine
    ports:
      - 5432:5432  # enables connecting locally via psql
    environment:
      POSTGRES_DB: qwic_db
      POSTGRES_HOST_AUTH_METHOD: trust