const profiles = [
  {
    src: "/gallery/CoChair-Beth.jpg",
    alt: "Beth Armstrong, Co-Chair",
    name: "Beth Armstrong",
    role: "Co-Chair",
    portfolio: "Co-Chairs",
  },
  {
    src: "/gallery/CoChair-Teagan.jpg",
    alt: "Teagan Wright, Co-Chair",
    name: "Teagan Wright",
    role: "Co-Chair",
    portfolio: "Co-Chairs",
  },
  {
    src: "/gallery/Community-Naveini.jpg",
    alt: "Naveini Vasikaran, Vice-Chair of Community",
    name: "Naveini Vasikaran",
    role: "Vice-Chair of Community",
    portfolio: "Community",
  },
  {
    src: "/gallery/Community-Ella.jpg",
    alt: "Ella Millar-Maggi, Community Coordinator",
    name: "Ella Millar-Maggi",
    role: "Community Coordinator",
    portfolio: "Community",
  },
  {
    src: "/gallery/Community-Emma.jpg",
    alt: "Emma Leitch-Blais, Community Coordinator",
    name: "Emma Leitch-Blais",
    role: "Community Coordinator",
    portfolio: "Community",
  },
  {
    src: "/gallery/Community-Sophia.jpg",
    alt: "Sophia Wang, Community Coordinator",
    name: "Sophia Wang",
    role: "Community Coordinator",
    portfolio: "Community",
  },
  {
    src: "/gallery/Communtiy-Audree.JPG",
    alt: "Audree Jacob, Community Coordinator",
    name: "Audree Jacob",
    role: "Community Coordinator",
    portfolio: "Community",
  },
  {
    src: "/gallery/Community-Eshal.jpg",
    alt: "Eshal Mirza, First-Year Community Representative",
    name: "Eshal Mirza",
    role: "First-Year Community Representative",
    portfolio: "Community",
  },
  {
    src: "/gallery/Community-Baarathi.JPG",
    alt: "Baarathi R, First-Year Community Representative",
    name: "Baarathi R",
    role: "First-Year Community Representative",
    portfolio: "Community",
  },
  {
    src: "/gallery/Marketing-Renee.jpg",
    alt: "Renee Kim, Vice-Chair of Marketing",
    name: "Renee Kim",
    role: "Vice-Chair of Marketing",
    portfolio: "Marketing",
  },
  {
    src: "/gallery/Marketing-Karelle.jpg",
    alt: "Karelle Ngakam Samashi, Marketing Coordinator",
    name: "Karelle Ngakam Samashi",
    role: "Marketing Coordinator",
    portfolio: "Marketing",
  },
  {
    src: "/gallery/Marketing-Amanda.jpg",
    alt: "Amanda Zhu, Graphic Designer",
    name: "Amanda Zhu",
    role: "Graphic Designer",
    portfolio: "Marketing",
  },
  {
    src: "/gallery/Marketing-Katrina.jpg",
    alt: "Katrina Jin, Graphic Designer",
    name: "Katrina Jin",
    role: "Graphic Designer",
    portfolio: "Marketing",
  },
  {
    src: "/gallery/Marketing-Elisa.jpg",
    alt: "Elisa Goncalves, Web Developer",
    name: "Elisa Goncalves",
    role: "Web Developer",
    portfolio: "Marketing",
  },
  {
    src: "/gallery/Marketing-Jasmine.jpg",
    alt: "Jasmine Qin, Web Developer",
    name: "Jasmine Qin",
    role: "Web Developer",
    portfolio: "Marketing",
  },
  {
    src: "/gallery/Marketing-Anisa.jpeg",
    alt: "Aniso Kilas, Web Developer",
    name: "Aniso Kilas",
    role: "Web Developer",
    portfolio: "Marketing",
  },
  {
    src: "/gallery/Marketing-Eyinise.jpg",
    alt: "Eyinise Momolosho, First-Year Web Developer Representative",
    name: "Eyinise Momolosho",
    role: "First-Year Web Developer Representative",
    portfolio: "Marketing",
  },
  {
    src: "/gallery/Operations-Lauren.jpg",
    alt: "Lauren Lidhar, Vice-Chair of Operations",
    name: "Lauren Lidhar",
    role: "Vice-Chair of Operations",
    portfolio: "Operations",
  },
  {
    src: "/gallery/Operations-MariaK.png",
    alt: "Maria Kobilaski, Senior Advisor",
    name: "Maria Kobilaski",
    role: "Senior Advisor",
    portfolio: "Operations",
  },
  {
    src: "/gallery/Operations-Annika.jpg",
    alt: "Annika Tran, Operations Coordinator",
    name: "Annika Tran",
    role: "Operations Coordinator",
    portfolio: "Operations",
  },
  {
    src: "/gallery/Operations-MariaB.jpg",
    alt: "Maria Baig, Sponsorships Coordinator",
    name: "Maria Baig",
    role: "Operations Coordinator",
    portfolio: "Operations",
  },
  {
    src: "/gallery/Operations-Jeshna.jpg",
    alt: "Jeshna Kanduri, Finance Coordinator",
    name: "Jeshna Kanduri",
    role: "Finance Coordinator",
    portfolio: "Operations",
  },
  {
    src: "/gallery/Operations-McKenna.jpg",
    alt: "McKenna Halley, First-Year Operations Representative",
    name: "McKenna Halley",
    role: "First-Year Operations Representative",
    portfolio: "Operations",
  },
  {
    src: "/gallery/HackHer-Elizabeth.jpg",
    alt: "Elizabeth Bighiu, Vice-Chair of HackHer",
    name: "Elizabeth Bighiu",
    role: "Vice-Chair of HackHer",
    portfolio: "HackHer",
  },
  {
    src: "/gallery/HackHer-Deandra.JPG",
    alt: "Deandra Furtado, HackHer Coordinator",
    name: "Deandra Furtado",
    role: "HackHer Coordinator",
    portfolio: "HackHer",
  },
  {
    src: "/gallery/HackHer-Emma.jpg",
    alt: "Emma Heffernan, HackHer Coordinator",
    name: "Emma Heffernan",
    role: "HackHer Coordinator",
    portfolio: "HackHer",
  },
  {
    src: "/gallery/HackHer-Sara.jpg",
    alt: "Sara Rodriguez-Bowen, HackHer Coordinator",
    name: "Sara Rodriguez-Bowen",
    role: "HackHer Coordinator",
    portfolio: "HackHer",
  },
  {
    src: "/gallery/HackHer-Tasnin.jpg",
    alt: "Tasnin Binta Arif, First-Year HackHer Representative",
    name: "Tasnin Binta Arif",
    role: "First-Year HackHer Representative",
    portfolio: "HackHer",
  },
  {
    src: "/gallery/Mentorship-Lily.jpg",
    alt: "Lilyana Boraniev, Vice-Chair of Mentorship",
    name: "Lilyana Boraniev",
    role: "Vice-Chair of Mentorship",
    portfolio: "Mentorship",
  },
  {
    src: "/gallery/Mentorship-Gloria.jpg",
    alt: "Gloria Chen, Mentorship Coordinator",
    name: "Gloria Chen",
    role: "Mentorship Coordinator",
    portfolio: "Mentorship",
  },
  {
    src: "/gallery/Mentorship-Sydney.jpg",
    alt: "Sydney Kinnear, Mentorship Coordinator",
    name: "Sydney Kinnear",
    role: "Mentorship Coordinator",
    portfolio: "Mentorship",
  },
  {
    src: "/gallery/Mentorship-Darby.JPG",
    alt: "Darby Duggan, Mentorship Coordinator",
    name: "Darby Duggan",
    role: "Mentorship Coordinator",
    portfolio: "Mentorship",
  },
  {
    src: "/gallery/Mentorship-Shweta.png",
    alt: "Shweta Padda, Mentorship Coordinator",
    name: "Shweta Padda",
    role: "Mentorship Coordinator",
    portfolio: "Mentorship",
  },
  {
    src: "/gallery/Mentorship-Anah.jpg",
    alt: "Anah Merchant, First-Year Mentorship Coordinator",
    name: "Anah Merchant",
    role: "First-Year Mentorship Coordinator",
    portfolio: "Mentorship",
  },
];

export default profiles;
